DROP TABLE IF EXISTS SPEND_INFO;
DROP TABLE IF EXISTS SPEND_MONEY_DETAIL;

CREATE TABLE SPEND_INFO (
	TOKEN VARCHAR(3) PRIMARY KEY,
	SPEND_USER_ID INT,
	ROOM_ID VARCHAR(200),
	SPEND_TIME TIMESTAMP,
	TOTAL_MONEY LONG,
	ALL_RECEIVED_YN VARCHAR(3)
) as select * from CSVREAD('classpath:data/뿌리기정보.csv');


CREATE TABLE SPEND_MONEY_DETAIL (
	TOKEN VARCHAR(3),
	SPEND_ID VARCHAR(3),
	ONE_TIME_MONEY LONG,
	RECEIVED_YN VARCHAR(3),
	RECEIVED_USER_ID INT,
	PRIMARY KEY(TOKEN, SPEND_ID)
) as select * from CSVREAD('classpath:data/뿌리기별금액정보.csv');